### ISSUE TITLE
change website favicon

### ISSUE THREAD

**Issue by wardappeltans** [iobis/edna-dashboard#100]
it is now similar to OBIS. Perhaps use a helix.

**Comment by pieterprovoost** [comment]
We can use the one from the eDNA samples app: https://github.com/iobis/edna-samples/blob/master/public/favicon.ico

**Comment by wardappeltans** [comment]
I still see the OBIS favicon

**Comment by pieterprovoost** [comment]
@wardappeltans Try a hard refresh.
