### ISSUE TITLE
Add requirements.R to the prepare_data.R or to Action (?)

### ISSUE THREAD

**Issue by silasprincipe** [iobis/edna-dashboard#109]
My last build didn't work because a package used in the climate code is missing. This package was added to the `requirements.R`, but it is not run in the action, right?

@pieterprovoost  what is the best approach?

1. Add it to prepare_data.R
2. Add it to the action
3. Run just once in the server

I don't anticipate new changes in the requirements very often, so 3 may be ok.

**Comment by pieterprovoost** [comment]
This should be installed during the container build, I'm rebuilding now.
