### ISSUE TITLE
Belize: filtering climate tab on CR does not return any species

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/edna-dashboard#120]
For at least Belize, filtering the climate tab on CR does not return any species. This is after regenerating data files, see https://github.com/iobis/edna-dashboard/actions/runs/12168394273/job/33939108134.

@silasprincipe I can look into this if necessary.

**Comment by silasprincipe** [comment]
There was a problem on `climate_server.R` that was not filtering by any input in fact. Solved in last commit.
