### ISSUE TITLE
source of common names?

### ISSUE THREAD

**Issue by wardappeltans** [iobis/edna-dashboard#130]
sometimes it displays un-common common names. what is the source? it is different from what we display on OBIS. would be better if we use what is in OBIS. that also has not only English common names.

**Comment by pieterprovoost** [comment]
It looks like common names are taken from FishBase and SeaLifeBase, although the table with WoRMS vernaculars is available in the supporting data folder.

**Comment by silasprincipe** [comment]
Changed for WoRMS table (`vernacular.txt`, loaded in server-start). Added 'Source: WoRMS'
