### ISSUE TITLE
source of species info missing

### ISSUE THREAD

**Issue by wardappeltans** [iobis/edna-dashboard#137]
the species pop-ups have great info but there is no credit to the source. 

Can this be easily added?

if not perhaps we need to remove it for now until we have solved this.

**Comment by silasprincipe** [comment]
Added source. Not sure why link to FishBase was removed from modal, as this is the source of the information. I kept without it, but I think we should keep...

**Comment by pieterprovoost** [comment]
@silasprincipe See https://github.com/iobis/edna-dashboard/issues/136

**Comment by silasprincipe** [comment]
@pieterprovoost thanks for pointing that. It should now be possible to introduce the link again, because the source is included in the new table. I will work on that.
