### ISSUE TITLE
Responsiveness not ideal on mobile screens

### ISSUE THREAD

**Issue by silasprincipe** [iobis/edna-dashboard#138]
The responsiveness is not looking good on small screens:

<img width="409" alt="image" src="https://github.com/user-attachments/assets/e472651a-e1cb-4911-b6d7-4adf3356a75a">

It seems that the problem is the use of `.text-nowrap` in the title.

**Comment by pieterprovoost** [comment]
I will make some adjustments, the stats boxes are also causing issues.
