### ISSUE TITLE
"Select site" remains very large when returning home

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/edna-dashboard#59]

**Comment by silasprincipe** [comment]
@pieterprovoost apparently is solved.

**Comment by silasprincipe** [comment]
Could you add a screenshot?

**Comment by pieterprovoost** [comment]
https://github.com/user-attachments/assets/5917a124-4f80-4860-a308-680a8f775f9b

**Comment by silasprincipe** [comment]
My last commit should solve that problem. I have not merged on main yet.
